spring.application.name=BDA_backend
server.port=8090

spring.datasource.url = jdbc:postgresql://localhost:5432/urbanismo_ciudades

spring.datasource.username = postgres
spring.datasource.password = a

